# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FgoPluto' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  swift_version = "3.0"

  # Pods for FgoPluto
  pod 'SnapKit', '~> 3.2.0'
  pod 'Alamofire', '~> 4.4'
  pod 'PromiseKit', '~> 4.0'
  pod 'RealmSwift', '2.10.2' 
  pod 'GMStepper', '~> 2.0.1'
  pod 'RangeSeekSlider', '~> 1.7.0'
 
  target 'FgoPlutoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FgoPlutoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '3.2'
      end
    end
  end

end
